config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # for JSON
  # ジャンル一覧
  get    '/api/genres' => 'genres#index'
  get    '/api/genres/update' => 'genres#update'

  # 板一覧(たいした情報は入っていない)
  get    '/api/boards' => 'boards#index'

  # 板情報(たいした情報は入っていない)
  get    '/api/boards/:board_name' => 'boards#show'

  # スレ一覧
  get    '/api/boards/:board_name/thres' => 'thres#index'

  # スレ情報(タイトル, NGID, bookmarkなど)
  get    '/api/boards/:board_name/thres/:thre_num' => 'thres#show'

  # レス一覧
  get    '/api/boards/:board_name/thres/:thre_num/resps' => 'resps#index'
  delete '/api/boards/:board_name/thres/:thre_num/resps' => 'resps#delete_all'

  # 特定のレス(150-210など)
  get    '/api/boards/:board_name/thres/:thre_num/resps/:resp_num' => 'resps#show'

  # ブックマーク用
  post   '/api/boards/:board_name/thres/:thre_num/bookmark' => 'bookmarks#new'
  get    '/api/boards/:board_name/thres/:thre_num/bookmark' => 'bookmarks#show'
  delete '/api/boards/:board_name/thres/:thre_num/bookmark' => 'bookmarks#delete'

  # アクセス履歴
  get    '/api/access_histories' => 'access_histories#index'

  # リダイレクト用ページ
  get '/redirect' => 'redirect#index'
end

app/models/access_history.rb
class AccessHistory < ApplicationRecord
  belongs_to :board
  belongs_to :thre

  def self.update(thre)
    history = find_or_create_by(thre_id: thre.id)
    history.update_attributes(board_id: thre.board.id)
    history.touch
  end

  def self.mra(board = nil)
    where(board_id: board).order(updated_at: 'DESC').limit(ACCESS_HISTORIES_LIMIT)
  end
end

app/controllers/access_histories_controller.rb
class AccessHistoriesController < ApplicationController
  def index
    access_histories = AccessHistory.all.order(id: 'desc').limit(15).map do |history|
      board = Board.find(history.board_id)
      thre = board.thres.find(history.thre_id)
      {
        board: board.ename,
        boardName: board.jname,
        thre: thre.num,
        title: thre.title,
      }
    end
    render json: access_histories
  end
end

app/helpers/access_histories_helper.rb
module AccessHistoriesHelper
end

app/views/access_histories/_form.html.erb
<%= form_with(model: access_history, local: true) do |form| %>
  <% if access_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(access_history.errors.count, "error") %> prohibited this access_history from being saved:</h2>

      <ul>
      <% access_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :board_id %>
    <%= form.number_field :board_id %>
  </div>

  <div class="field">
    <%= form.label :thre_id %>
    <%= form.number_field :thre_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/access_histories/edit.html.erb
<h1>Editing Access History</h1>

<%= render 'form', access_history: @access_history %>

<%= link_to 'Show', @access_history %> |
<%= link_to 'Back', access_histories_path %>

app/views/access_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Access Histories</h1>

<table>
  <thead>
    <tr>
      <th>Board</th>
      <th>Thre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @access_histories.each do |access_history| %>
      <tr>
        <td><%= access_history.board_id %></td>
        <td><%= access_history.thre_id %></td>
        <td><%= link_to 'Show', access_history %></td>
        <td><%= link_to 'Edit', edit_access_history_path(access_history) %></td>
        <td><%= link_to 'Destroy', access_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Access History', new_access_history_path %>

app/views/access_histories/new.html.erb
<h1>New Access History</h1>

<%= render 'form', access_history: @access_history %>

<%= link_to 'Back', access_histories_path %>

app/views/access_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Board:</strong>
  <%= @access_history.board_id %>
</p>

<p>
  <strong>Thre:</strong>
  <%= @access_history.thre_id %>
</p>

<%= link_to 'Edit', edit_access_history_path(@access_history) %> |
<%= link_to 'Back', access_histories_path %>