config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # for JSON
  # ジャンル一覧
  get    '/api/genres' => 'genres#index'
  get    '/api/genres/update' => 'genres#update'

  # 板一覧(たいした情報は入っていない)
  get    '/api/boards' => 'boards#index'

  # 板情報(たいした情報は入っていない)
  get    '/api/boards/:board_name' => 'boards#show'

  # スレ一覧
  get    '/api/boards/:board_name/thres' => 'thres#index'

  # スレ情報(タイトル, NGID, bookmarkなど)
  get    '/api/boards/:board_name/thres/:thre_num' => 'thres#show'

  # レス一覧
  get    '/api/boards/:board_name/thres/:thre_num/resps' => 'resps#index'
  delete '/api/boards/:board_name/thres/:thre_num/resps' => 'resps#delete_all'

  # 特定のレス(150-210など)
  get    '/api/boards/:board_name/thres/:thre_num/resps/:resp_num' => 'resps#show'

  # ブックマーク用
  post   '/api/boards/:board_name/thres/:thre_num/bookmark' => 'bookmarks#new'
  get    '/api/boards/:board_name/thres/:thre_num/bookmark' => 'bookmarks#show'
  delete '/api/boards/:board_name/thres/:thre_num/bookmark' => 'bookmarks#delete'

  # アクセス履歴
  get    '/api/access_histories' => 'access_histories#index'

  # リダイレクト用ページ
  get '/redirect' => 'redirect#index'
end

app/models/thre.rb
class Thre < ApplicationRecord
  belongs_to :board
  has_many :resps
  has_one :bookmark, dependent: :destroy
  has_one :access_history, dependent: :destroy

  validates :num, uniqueness: { scope: [ :board_id ]}

  def update_resps
    length = resps.size
    start_num = length + 1

    raw_res = get_resps(start_num)
    return if raw_res.nil?

    resp_list = parse_resp(raw_res)

    queries = []
    resp_list.each do |resp|
      r = resps.find_or_create_by(num: resp[:id])
      r.name     = resp[:name]
      r.userid   = resp[:userid]
      r.email    = resp[:email]
      r.wacchoi  = resp[:wacchoi]
      r.date     = resp[:date]
      r.contents = resp[:contents]
      queries << r
    end
    Resp.import queries, on_duplicate_key_update: {
      conflict_target: [:id],
      columns: [:name, :userid, :email, :wacchoi, :date, :contents]
    }
    queries
  end

  private
  def get_resps(start_num)
    uri = URI.parse("#{board.server}/test/read.cgi/#{board.ename}/#{num}/#{start_num}-")
    Net::HTTP.start(uri.host, uri.port) do |http|
      res = http.get(uri.path, 'User-Agent' => USER_AGENT)
      if res.kind_of? Net::HTTPOK
        return res.body
      else
        return nil
      end
    end
  end

  def parse_resp(html)
    doc = Nokogiri::HTML.parse(html, nil, 'Shift_JIS')

    # 新しいタイプ
    if doc.at_css('div.thread')
      return parse_new_format(doc)
    end

    # 古いタイプ
    if doc.at_css('dl.thread')
      return parse_old_format(doc)
    end

    # pinkタイプ
    if doc.at_css('dl.post')
      return parse_pink_format(doc)
    end
  end

  def parse_new_format(doc)
    resps = []

    doc.css('div.post').each do |parent|
      res = {:id => 0}
      res[:id] = parent.attributes['id'].to_s
      res[:userid] = parent.attributes['data-userid'].to_s

      name_tag = parent.at_css('.name')
      a_href = name_tag.at_css('a')
      if a_href
        # メールあり
        res[:email] = a_href.attributes['href'].to_s.gsub(/mailto:/, '')
        res[:name] = a_href.content
      else
        # メールなし
        res[:email] = ''
        res[:name] = name_tag.at_css('b').content
      end

      res[:wacchoi] = ''
      name_tag.to_s.match(/<\/b>(.*)<b>/) do |m|
        res[:wacchoi] = m[1]
      end

      # &. はUTF-8への変換に失敗して date_str_arr が読み取れない場合への対策
      date_str_arr = parent.at_css('.date')&.content&.split(' ') || ['', '']

      # date_str_arr[1].presenceはあぼーん対策
      res[:date] = date_str_arr[0] + ' ' + (date_str_arr[1].presence || '')

      # &. はUTF-8への変換に失敗して res[:contents] が読み取れない場合への対策
      res[:contents] = parent.at_css('div.message')&.inner_html

      resps << res
    end

    return resps
  end

  def parse_old_format(doc)
    resps = []

    doc.css('dt').each do |parent|
      res = {:id => 0}

      id_matched = parent.children.first.content.match(/^([0-9]+)/)
      res[:id] = id_matched[1]

      a_href = parent.at_css('a')
      if a_href
        # メールあり
        res[:email] = a_href.attributes['href'].to_s.gsub(/mailto:/, '')
        res[:name] = a_href.content
      else
        # メールなし
        res[:email] = ''
        res[:name] = parent.at_css('font b').content
      end

      date_id_text = parent.children.last.to_s
      date_id_text.gsub!(/^[^0-9]*/, '')

      sp = date_id_text.split(' ')
      res[:date] = sp[0] + ' ' + sp[1]
      res[:userid] = sp[2].presence || ''

      res[:wacchoi] = ''
      parent.to_s.match(/<\/b>(.*)<b>/) do |m|
        res[:wacchoi] = m[1]
      end

      resps << res
    end

    doc.css('dd').each_with_index do |parent, index|
      resps[index][:contents] = parent.inner_html
    end

    return resps
  end

  def parse_pink_format(doc)
    resps = []

    doc.css('dl.post').each do |parent|
      res = {:id => 0}
      res[:id] = parent.attributes['id'].to_s
      res[:userid] = parent.attributes['data-userid'].to_s

      span_name = parent.at_css('span.name')
      a_href = span_name.at_css('a')
      if a_href
        # メールあり
        res[:email] = a_href.attributes['href'].to_s.gsub(/mailto:/, '')
        res[:name] = a_href.content
      else
        # メールなし
        res[:email] = ''
        res[:name] = span_name.at_css('b').content
      end

      res[:wacchoi] = ''

      date_str_arr = parent.at_css('span.date').content.split(' ')
      # date_str_arr[1].presenceはあぼーん対策
      res[:date] = date_str_arr[0] + ' ' + (date_str_arr[1].presence || '')

      res[:contents] = parent.at_css('dd').inner_html

      resps << res
    end

    return resps
  end
end

app/controllers/thres_controller.rb
class ThresController < ApplicationController
  before_action :set_board

  def index
    if params[:cache].blank?
      thres = @board.update_thres
    else
      # title に "1: ", "2: " と含まれるものを順に抽出する
      thres = (1..20).map { |n|
        @board.thres.where('title like ?', "#{n}: %").order(updated_at: 'DESC').first
      }.filter { |n| n }
    end

    render json: thres.map { |t|
      {
        num: t.num,
        title: t.title,
      }
    }
  end

  def show
    thre = @board.thres.find_by_num(params[:thre_num])
    bookmark = thre.bookmark
    bookmark_num = bookmark ? bookmark.bookmark_num : 0
    render json: {
      board_id: thre.board.ename,
      thre_id: thre.num,
      title: thre.title,
      bookmark: bookmark_num,
    }
  end

  private
  def set_board
    @board = Board.find_by_ename(params[:board_name])
    if @board.nil?
      render json: { message: "#{params[:board_name]} not found"}, status: 404
    end
  end
end

app/helpers/thres_helper.rb
module ThresHelper
end

app/views/thres/_form.html.erb
<%= form_with(model: thre, local: true) do |form| %>
  <% if thre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thre.errors.count, "error") %> prohibited this thre from being saved:</h2>

      <ul>
      <% thre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :board_id %>
    <%= form.number_field :board_id %>
  </div>

  <div class="field">
    <%= form.label :num %>
    <%= form.text_field :num %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/thres/edit.html.erb
<h1>Editing Thre</h1>

<%= render 'form', thre: @thre %>

<%= link_to 'Show', @thre %> |
<%= link_to 'Back', thres_path %>

app/views/thres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Thres</h1>

<table>
  <thead>
    <tr>
      <th>Board</th>
      <th>Num</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thres.each do |thre| %>
      <tr>
        <td><%= thre.board_id %></td>
        <td><%= thre.num %></td>
        <td><%= thre.title %></td>
        <td><%= link_to 'Show', thre %></td>
        <td><%= link_to 'Edit', edit_thre_path(thre) %></td>
        <td><%= link_to 'Destroy', thre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thre', new_thre_path %>

app/views/thres/new.html.erb
<h1>New Thre</h1>

<%= render 'form', thre: @thre %>

<%= link_to 'Back', thres_path %>

app/views/thres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Board:</strong>
  <%= @thre.board_id %>
</p>

<p>
  <strong>Num:</strong>
  <%= @thre.num %>
</p>

<p>
  <strong>Title:</strong>
  <%= @thre.title %>
</p>

<%= link_to 'Edit', edit_thre_path(@thre) %> |
<%= link_to 'Back', thres_path %>