config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # for JSON
  # ジャンル一覧
  get    '/api/genres' => 'genres#index'
  get    '/api/genres/update' => 'genres#update'

  # 板一覧(たいした情報は入っていない)
  get    '/api/boards' => 'boards#index'

  # 板情報(たいした情報は入っていない)
  get    '/api/boards/:board_name' => 'boards#show'

  # スレ一覧
  get    '/api/boards/:board_name/thres' => 'thres#index'

  # スレ情報(タイトル, NGID, bookmarkなど)
  get    '/api/boards/:board_name/thres/:thre_num' => 'thres#show'

  # レス一覧
  get    '/api/boards/:board_name/thres/:thre_num/resps' => 'resps#index'
  delete '/api/boards/:board_name/thres/:thre_num/resps' => 'resps#delete_all'

  # 特定のレス(150-210など)
  get    '/api/boards/:board_name/thres/:thre_num/resps/:resp_num' => 'resps#show'

  # ブックマーク用
  post   '/api/boards/:board_name/thres/:thre_num/bookmark' => 'bookmarks#new'
  get    '/api/boards/:board_name/thres/:thre_num/bookmark' => 'bookmarks#show'
  delete '/api/boards/:board_name/thres/:thre_num/bookmark' => 'bookmarks#delete'

  # アクセス履歴
  get    '/api/access_histories' => 'access_histories#index'

  # リダイレクト用ページ
  get '/redirect' => 'redirect#index'
end

app/models/resp.rb
class Resp < ApplicationRecord
  belongs_to :thre
  validates :num, uniqueness: { scope: :thre_id }
end

app/controllers/resps_controller.rb
class RespsController < ApplicationController
  before_action :set_thre

  def index
    if params[:cache].blank?
      @thre.update_resps
    end


    if params[:bookmark].present?
      start = @thre.bookmark ? @thre.bookmark.bookmark_num : 1
      last  = start + 49
      resps = @thre.resps.where(num: start..last).order(:num)
    else
      resps = @thre.resps.order(:num)
    end

    render json: {
      resps: resps.map { |r|
        {
          num:      r.num,
          name:     r.name,
          userid:   r.userid,
          email:    r.email,
          wacchoi:  r.wacchoi,
          date:     r.date,
          contents: r.contents,
        }
      },
      bookmark: @thre.bookmark ? @thre.bookmark.bookmark_num : 0,
      total: @thre.resps.size,
    }

    AccessHistory.update(@thre)
  end

  def show
    if params[:resp_num] !~ /\A[0-9,-]+\z/
      return render json: { message: "invalid format #{params[:resp_num]}" }, status: 400
    end

    nums = params[:resp_num].split(',').map do |list|
      if list.index('-').nil?
        # - を含まない場合
        list.to_i
      elsif list =~ /\A-[0-9]+\z/
        # - で始まる場合
        1..list.gsub('-', '').to_i
      elsif list =~ /\A[0-9]+-\z/
        # - で終わる場合
        list.gsub('-', '').to_i..1002
      else
        md = list.split('-')
        md[0].to_i..md[1].to_i
      end
    end

    # 要求された最大レス番が現在保存しているレス数を超えていたら
    # ネットワークから最新のレスを取得する
    max_num = nums.reduce(1) { |a, b| [*a, *b].max }
    if max_num > @thre.resps.size
      @thre.update_resps
    end

    resps = @thre.resps.where(num: nums).order(:num)

    render json: {
      resps: resps.map { |r|
        {
          num:      r.num,
          name:     r.name,
          userid:   r.userid,
          email:    r.email,
          wacchoi:  r.wacchoi,
          date:     r.date,
          contents: r.contents,
        }
      },
      bookmark: @thre.bookmark ? @thre.bookmark.bookmark_num : 0,
      total: @thre.resps.size,
    }

    AccessHistory.update(@thre)
  end

  def delete_all
    @thre.resps.delete_all
    render head: :no_content
  end

  private
  def set_thre
    @board = Board.find_by_ename(params[:board_name])
    if @board.nil?
      render json: { message: "#{params[:board_name]} not found"}, status: 404
    end
    @thre = @board.thres.find_by_num(params[:thre_num])
    if @thre.nil?
      render json: { message: "#{params[:thre_num]} not found"}, status: 404
    end
  end
end

app/helpers/resps_helper.rb
module RespsHelper
end

app/views/resps/_form.html.erb
<%= form_with(model: resp, local: true) do |form| %>
  <% if resp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resp.errors.count, "error") %> prohibited this resp from being saved:</h2>

      <ul>
      <% resp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :thre_id %>
    <%= form.number_field :thre_id %>
  </div>

  <div class="field">
    <%= form.label :num %>
    <%= form.number_field :num %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :userid %>
    <%= form.text_field :userid %>
  </div>

  <div class="field">
    <%= form.label :wacchoi %>
    <%= form.text_field :wacchoi %>
  </div>

  <div class="field">
    <%= form.label :contents %>
    <%= form.text_area :contents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resps/edit.html.erb
<h1>Editing Resp</h1>

<%= render 'form', resp: @resp %>

<%= link_to 'Show', @resp %> |
<%= link_to 'Back', resps_path %>

app/views/resps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resps</h1>

<table>
  <thead>
    <tr>
      <th>Thre</th>
      <th>Num</th>
      <th>Name</th>
      <th>Email</th>
      <th>Date</th>
      <th>Userid</th>
      <th>Wacchoi</th>
      <th>Contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resps.each do |resp| %>
      <tr>
        <td><%= resp.thre_id %></td>
        <td><%= resp.num %></td>
        <td><%= resp.name %></td>
        <td><%= resp.email %></td>
        <td><%= resp.date %></td>
        <td><%= resp.userid %></td>
        <td><%= resp.wacchoi %></td>
        <td><%= resp.contents %></td>
        <td><%= link_to 'Show', resp %></td>
        <td><%= link_to 'Edit', edit_resp_path(resp) %></td>
        <td><%= link_to 'Destroy', resp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resp', new_resp_path %>

app/views/resps/new.html.erb
<h1>New Resp</h1>

<%= render 'form', resp: @resp %>

<%= link_to 'Back', resps_path %>

app/views/resps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Thre:</strong>
  <%= @resp.thre_id %>
</p>

<p>
  <strong>Num:</strong>
  <%= @resp.num %>
</p>

<p>
  <strong>Name:</strong>
  <%= @resp.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @resp.email %>
</p>

<p>
  <strong>Date:</strong>
  <%= @resp.date %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @resp.userid %>
</p>

<p>
  <strong>Wacchoi:</strong>
  <%= @resp.wacchoi %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @resp.contents %>
</p>

<%= link_to 'Edit', edit_resp_path(@resp) %> |
<%= link_to 'Back', resps_path %>